DOCKER_CMD := docker
DOCKER_COMPOSE_CMD := docker-compose

DOCKER_COMPOSE_CONTAINER := vimhelp_jp_dev
DOCKER_COMPOSE_SERVICE := dev
DOCKER_COMPOSE_DAEMON := true

DOCKER_COMPOSE_BUILD := ${DOCKER_COMPOSE_CMD} build

ifeq (${DOCKER_COMPOSE_DAEMON},true)
	DOCKER_COMPOSE_UP := ${DOCKER_COMPOSE_CMD} up -d
else
	DOCKER_COMPOSE_UP := ${DOCKER_COMPOSE_CMD} up
endif


default: log

build:
	${DOCKER_COMPOSE_BUILD} ${DOCKER_COMPOSE_SERVICE}

up: build
	${DOCKER_COMPOSE_UP} ${DOCKER_COMPOSE_SERVICE}

log: up
	${DOCKER_CMD} logs -f ${DOCKER_COMPOSE_CONTAINER}

clean:
	${DOCKER_COMPOSE_CMD} rm -f ${DOCKER_COMPOSE_SERVICE}

.PHONY: build up log clean
